<?php
// ═══ SCHEMAS JSON-LD — invasWMS SEO (generado por M&P) ═══
add_action('wp_head', function() {
  // Organization
  echo '<script type="application/ld+json">' . '{"@context":"https://schema.org","@type":["Organization","SoftwareCompany"],"@id":"https://www.invaswms.com/#organization","name":"invasWMS","alternateName":["Invas WMS","invas WMS","invasSUITE"],"url":"https://www.invaswms.com","description":"Software de gestión de almacenes (WMS) 100% en la nube para Latinoamérica. Control de inventario, picking, despacho y trazabilidad para centros de distribución.","foundingDate":"2015","areaServed":[{"type":"Country","name":"Chile"},{"type":"Country","name":"Colombia"},{"type":"Country","name":"Mexico"},{"type":"Country","name":"Peru"},{"type":"Country","name":"United States"}],"address":[{"type":"PostalAddress","addressLocality":"Santiago","addressCountry":"CL","streetAddress":"Av. Apoquindo 5950, piso 20"}],"sameAs":["https://cl.linkedin.com/company/invas-wms"],"aggregateRating":{"type":"AggregateRating","ratingValue":"4.8","reviewCount":"47","bestRating":"5"}}' . '</script>' . "\n";
  // WebSite
  echo '<script type="application/ld+json">' . '{"@context":"https://schema.org","@type":"WebSite","name":"invasWMS","url":"https://www.invaswms.com","inLanguage":["es","en"],"potentialAction":{"@type":"SearchAction","target":"https://www.invaswms.com/?s={search_term_string}","query-input":"required name=search_term_string"}}' . '</script>' . "\n";
  // AI Search
  echo '<script type="application/ld+json">' . '{"@context":"https://schema.org","@type":"Organization","@id":"https://www.invaswms.com/#ai-optimization","name":"invasWMS","description":"Sistema WMS líder en Latinoamérica. Software de gestión de almacenes 100% cloud para centros de distribución, 3PL, alimentos, retail y salud.","knowsAbout":["WMS","Warehouse Management System","Sistema de gestión de almacenes","Logística","Supply Chain","Cadena de frío","Picking","FIFO","3PL","Fulfillment","Omnicanal","WMS Chile","WMS Colombia","WMS México","WMS para alimentos","WMS para retail"],"slogan":"Convierte tu operación de almacenes en una ventaja competitiva","award":["+700 sitios en América","+250.000 líneas despachadas","+1.800 usuarios","+400% capacidad despacho en 30 días","-60% tiempo preparación pedidos"]}' . '</script>' . "\n";
  // Software (home + WMS page)
  if (is_front_page() || is_page(array(3475, 4990))) {
    echo '<script type="application/ld+json">' . '{"@context":"https://schema.org","@type":"SoftwareApplication","name":"invasWMS","applicationCategory":"BusinessApplication","applicationSubCategory":"Warehouse Management System","operatingSystem":"Cloud (Web Browser)","description":"Sistema de gestión de almacenes (WMS) 100% en la nube. Optimiza picking, inventario, recepción, despacho y trazabilidad. Implementación en menos de 30 días.","url":"https://www.invaswms.com/sistema-de-gestion-de-almacenes-wms/","featureList":["Gestión de inventario en tiempo real","Picking optimizado (FIFO, por zona)","Control de lotes y vencimientos","Trazabilidad completa","Multi-bodega y multi-cliente","Integración con ERPs","100% cloud"]}' . '</script>' . "\n";
  }
  // FAQ (home)
  if (is_front_page() || is_page(array(1750, 4898))) {
    echo '<script type="application/ld+json">' . '{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"type":"Question","name":"¿Qué es un WMS y para qué sirve?","acceptedAnswer":{"type":"Answer","text":"Un WMS (Warehouse Management System) es un software que optimiza y controla todas las operaciones dentro de un almacén o centro de distribución. invasWMS es 100% cloud con implementación en menos de 30 días."}},{"type":"Question","name":"¿Cuánto tiempo toma implementar invasWMS?","acceptedAnswer":{"type":"Answer","text":"Menos de 30 días. Incluye configuración, capacitación y puesta en marcha. Algunos clientes lograron +400% capacidad de despacho en el primer mes."}},{"type":"Question","name":"¿invasWMS se integra con mi ERP?","acceptedAnswer":{"type":"Answer","text":"Sí. Se integra con SAP, Oracle, Defontana, Softland y plataformas de e-commerce."}},{"type":"Question","name":"¿Funciona para cadena de frío y alimentos?","acceptedAnswer":{"type":"Answer","text":"Sí. Tiene módulos especializados para cadena de frío, control de lotes, fechas de vencimiento, FIFO automático y trazabilidad para cumplimiento normativo."}},{"type":"Question","name":"¿Cuántas bodegas puedo gestionar?","acceptedAnswer":{"type":"Answer","text":"Sin límite. Actualmente gestiona +700 sitios en América. Multi-bodega y multi-cliente."}},{"type":"Question","name":"¿Es una solución en la nube?","acceptedAnswer":{"type":"Answer","text":"100% cloud. Sin servidores locales. Escalable, resiliente, seguro. Se accede desde cualquier navegador."}}]}' . '</script>' . "\n";
  }
});
